### PR TITLE
Fix doxygen generation

### LINKED ISSUE #7: Autogenerated docs are empty
Travis is running doxygen and deploying the website, but the site doesn't have any ping class documentation.

site: http://docs.bluerobotics.com/ping-arduino/

search initial deployment for 'ping': https://github.com/bluerobotics/ping-arduino/commit/c119600253cde6d18239e40087b65366d31c51d8

### PR DESCRIPTION
**Pull request by Williangalvani**
The `update-gh-pages.sh` script is calling doxygen from the git repository root directory, so the `../src` makes Doxygen try to get src files from outside of the git repo. It is also not pointing to `docs/Doxyfile`

Fix #7

### CODE REVIEW

File: doc/Doxyfile [hunk 1]
```diff
@@ -791,7 +791,7 @@ WARN_LOGFILE           =
 # spaces. See also FILE_PATTERNS and EXTENSION_MAPPING
 # Note: If this tag is empty the current directory is searched.
 
-INPUT                  = ../src
```
Comment (jaxxzer) [inline doc/Doxyfile]: I believe this wrong and the commit should be removed

Comment (jaxxzer) [reply doc/Doxyfile]: `../src` is indeed the location of the source directory relative to the doxyfile. The fix for this pr should be to run doxygen from inside the doc directory, I think.

Comment (Williangalvani) [reply doc/Doxyfile]: I agree, updated.

File: doc/update-gh-pages.sh [hunk 2]
```diff
@@ -42,13 +42,11 @@ else
 fi
 
 echob "Build doxygen documentation."
-if ! doxygen "${script_path}"; then
+cd $script_path
+if ! doxygen "Doxyfile"; then
```
Comment (jaxxzer) [inline doc/update-gh-pages.sh]:
```suggestion
if ! cd $script_path && doxygen "Doxyfile"; then
```

File: doc/update-gh-pages.sh [hunk 3]
```diff
@@ -42,13 +42,11 @@ else
...
     echo "- Doxygen generation failed."
     exit 1
 fi
-mv "${project_path}/html/" "${script_path}"
-echo "- Check files"
```
Comment (jaxxzer) [inline doc/update-gh-pages.sh]: Why remove the check?

Comment (Williangalvani) [reply doc/update-gh-pages.sh]: mistake, my bad
